name: Testing

on:
  push:
    branches: master

jobs:
  foo:
    runs-on: linux-latest
    steps:
    - if: "0"
      name: first
      run: |
        echo a

  bar:
    needs: foo
    runs-on: linux-latest
    steps:
    - name: first
      run: |
        echo b


















