name: Testing

on:
  push:
    branches: master

jobs:

  foo:
    outputs:
      HELLO: test
    runs-on: ubuntu-latest
    steps:
      - id: first
        run: |
          echo '::set-output name=HELLO::there'

  bar:
    needs: foo
    runs-on: ubuntu-latest
    if: needs.foo.outputs.HELLO == 'there'
    steps:
    - name: second
      run: |
        echo b


















