name: Testing

on:
  push:
    branches: master

jobs:
  runs-on: ubuntu-latest

  foo:
    outputs:
      status: ${{ steps.first.conclusion }}
    steps:
      - id: first
        run: |
          echo a

  bar:
    needs: foo
    if: needs.foo.outputs.status == 'success'
    steps:
    - name: second
      run: |
        echo b


















