name: Testing

on:
  push:
    branches: master

jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
    - if: "0"
      name: first
      run: |
        echo a

  bar:
    needs: foo.first
    runs-on: ubuntu-latest
    steps:
    - name: second
      run: |
        echo b


















